#!/usr/bin/env python3
"""
Lean POS migration assessor.

Offline, read-only, deterministic analysis of the repository's migration
readiness from legacy POS to Lean POS.

Outputs (written atomically under --output-dir):
  legacy-inventory.yaml   Machine-readable artifact inventory
  capability-map.yaml     Capability replacement status
  blockers.yaml           Issues blocking safe legacy retirement
  cutover-plan.yaml       Ordered implementation sequence
  README.md               Short operator guide (≤1800 tokens)

Exit codes:
  0  assessment complete — no cutover blockers
  1  assessment complete — blockers present
  2  invalid input or configuration
  3  repository state could not be assessed

Usage:
  python tools/pos/lean/assess_migration.py \\
    --repo-root . \\
    --generated-at 2026-07-18T22:00:00Z \\
    --output-dir project/lean/migration
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

import yaml

from tools.pos.lean.schemas import (
    REPO_ROOT as DEFAULT_REPO_ROOT,
    MIGR_INVALID_INPUT,
    MIGR_WRITE_OUTSIDE_SCOPE,
)
from tools.pos.lean.migration import (
    build_legacy_inventory,
    build_capability_map,
    build_blockers,
    build_cutover_plan,
)


# ---------------------------------------------------------------------------
# README content
# ---------------------------------------------------------------------------

README_CONTENT = """\
# Lean POS Migration Assessment

Generated by `tools/pos/lean/assess_migration.py`. **Not canonical.**

## Files in this directory

| File | Purpose |
|---|---|
| `legacy-inventory.yaml` | Every legacy POS artifact, its role, consumers, and disposition |
| `capability-map.yaml` | Each required capability mapped to its lean replacement or gap |
| `blockers.yaml` | Issues blocking safe legacy retirement |
| `cutover-plan.yaml` | Ordered cutover phases with verification and rollback |
| `README.md` | This file |

## Regenerate

```
python tools/pos/lean/assess_migration.py \\
  --repo-root . \\
  --generated-at $(date -u +%Y-%m-%dT%H:%M:%SZ) \\
  --output-dir project/lean/migration
```

Outputs are byte-identical for identical repository state and `--generated-at`.

## Current status

Assessment exits 0 (no open blockers). All 6 blockers resolved.

**Resolved decisions:**
- FD-001 (LEAN-POS-05): github_satisfies_pos_record_requirement — approved (BLKR-001 closed)
- FD-002 (LEAN-POS-05): manifest_resolution=update_hashes — approved (BLKR-002 closed)
- FD-003 (LEAN-POS-05): founder_merge_implies_acceptance — approved (BLKR-004 closed)
- FD-004 (LEAN-POS-05): lean_integrity_checker=approved_minimal — approved (BLKR-006 closed)
- BLKR-003 (LEAN-POS-08): CI switched to lean validator, generator, and integrity checker
- BLKR-005 (LEAN-POS-08): AGENTS.md and CURRENT_STATE.md point to lean POS; MANAGER_INBOX deleted

## Capability summary

See `capability-map.yaml`. 19 capabilities replaced, 2 partially replaced,
0 blocked, 1 replaced with different mechanism.

## Cutover phases

| Phase | Name | Status |
|---|---|---|
| CUTOVER-01 | resolve_governance_and_integrity_blockers | complete |
| CUTOVER-02 | establish_canonical_lean_project_state | complete |
| CUTOVER-03 | switch_ci_and_documentation_entrypoints | complete |
| CUTOVER-04 | archive_historical_legacy_records | complete |
| CUTOVER-05 | remove_legacy_runtime_and_generated_views | complete |
| CUTOVER-06 | verify_lean_only_repository | pending (next) |

Each phase is independently reversible. Deletion is last (CUTOVER-05).
"""


# ---------------------------------------------------------------------------
# Atomic write (same as generate.py)
# ---------------------------------------------------------------------------

def _atomic_write(path: Path, content: str, output_dir: Path) -> None:
    """Write atomically; raise if path escapes output_dir."""
    try:
        path.resolve().relative_to(output_dir.resolve())
    except ValueError:
        raise PermissionError(
            f"[{MIGR_WRITE_OUTSIDE_SCOPE}] Write outside output scope: {path}"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".assess-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _dump_yaml(data: dict) -> str:
    return yaml.dump(data, default_flow_style=False, allow_unicode=True,
                     sort_keys=False, width=120)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Lean POS migration assessor. Offline, read-only, deterministic.",
    )
    parser.add_argument("--repo-root", default=str(DEFAULT_REPO_ROOT), metavar="PATH",
                        help="Repository root (default: autodetected)")
    parser.add_argument("--generated-at", metavar="ISO8601", required=False,
                        help="Override generation timestamp (for deterministic output)")
    parser.add_argument("--output-dir", metavar="PATH", required=True,
                        help="Directory to write assessment outputs")

    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    if not repo_root.is_dir():
        print(f"[{MIGR_INVALID_INPUT}] --repo-root is not a directory: {repo_root}",
              file=sys.stderr)
        return 2

    output_dir = Path(args.output_dir).resolve()

    generated_at = args.generated_at
    if not generated_at:
        import datetime
        generated_at = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    try:
        inventory = build_legacy_inventory(repo_root, generated_at)
    except Exception as exc:
        print(f"[M003] Failed to build legacy inventory: {exc}", file=sys.stderr)
        return 3

    try:
        cap_map = build_capability_map(generated_at)
    except Exception as exc:
        print(f"[M003] Failed to build capability map: {exc}", file=sys.stderr)
        return 3

    try:
        blockers = build_blockers(generated_at)
    except Exception as exc:
        print(f"[M003] Failed to build blockers: {exc}", file=sys.stderr)
        return 3

    try:
        cutover = build_cutover_plan(generated_at)
    except Exception as exc:
        print(f"[M003] Failed to build cutover plan: {exc}", file=sys.stderr)
        return 3

    outputs = {
        "legacy-inventory.yaml": _dump_yaml(inventory),
        "capability-map.yaml": _dump_yaml(cap_map),
        "blockers.yaml": _dump_yaml(blockers),
        "cutover-plan.yaml": _dump_yaml(cutover),
        "README.md": README_CONTENT,
    }

    for filename, content in sorted(outputs.items()):
        out_path = output_dir / filename
        try:
            _atomic_write(out_path, content, output_dir)
            print(f"Written: {out_path}")
        except Exception as exc:
            print(f"[ERROR] Failed to write {out_path}: {exc}", file=sys.stderr)
            return 1

    has_blockers = bool(blockers.get("blockers"))
    total = blockers.get("summary", {}).get("total_blockers", 0)
    high = blockers.get("summary", {}).get("by_severity", {}).get("high", 0)
    print(f"\nAssessment complete. Blockers: {total} ({high} high severity).")
    if has_blockers:
        print("Cutover is NOT ready. Resolve blockers before proceeding.")
        return 1

    print("No blockers found. Cutover may proceed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
