"""Strategy Layer (ADR-003).

Owns deterministic Strategy evaluation and Opportunity production. Narrower
dependency rule (ADR-004, ASA-CORE-005): may depend on strategies,
indicators, facts, reconciliation, and domain — not observation or
providers, even though both sit below strategies in the general pipeline
order (Constitution Law 4: Strategies consume knowledge, they do not
gather it).
"""

from strategies.components import (
    COMPONENT_IDENTITY_NAMESPACE,
    COMPONENT_IDENTITY_VERSION,
    BaseComponent,
    ComponentCategory,
    ComponentDefinition,
    ParameterDefinition,
    PortCardinality,
    PortDefinition,
    StrategyTypeReference,
    component_definition_data,
    component_identity,
)
from strategies.component_registry import (
    REGISTRY_IDENTITY_NAMESPACE,
    REGISTRY_IDENTITY_VERSION,
    SUPPORTED_COMPONENT_CAPABILITIES,
    ComponentRegistry,
)
from strategies.engine import (
    OPPORTUNITY_IDENTITY_NAMESPACE,
    OPPORTUNITY_IDENTITY_VERSION,
    evaluate_strategy,
    opportunity_identity,
)
from strategies.errors import (
    ComponentContractError,
    DuplicateStrategyRegistrationError,
    ExpressionCompileError,
    ExpressionError,
    ExpressionEvaluationError,
    GraphExecutionError,
    GraphValidationError,
    InvalidStrategyParameterError,
    ManifestSerializationError,
    ManifestValidationError,
    MissingIndicatorInputError,
    NoContributingFactsError,
    StrategyError,
    UnsupportedManifestSchemaError,
    UnknownStrategyIdError,
)
from strategies.runtime import (
    EVALUATION_IDENTITY_NAMESPACE,
    EVALUATION_IDENTITY_VERSION,
    GRAPH_IDENTITY_NAMESPACE,
    GRAPH_IDENTITY_VERSION,
    GRAPH_RUNTIME_VERSION,
    CompiledNode,
    CompiledStrategyGraph,
    ExecutionTrace,
    GraphExecutionResult,
    TraceEvent,
    compile_strategy_graph,
    execute_strategy_graph,
)
from strategies.expressions import (
    EXPRESSION_IDENTITY_NAMESPACE,
    EXPRESSION_IDENTITY_VERSION,
    EXPRESSION_LANGUAGE_VERSION,
    CompiledExpression,
    ExpressionLimits,
    ExpressionNode,
    ExpressionResult,
    ExpressionTrace,
    compile_expression,
    evaluate_expression,
)
from strategies.manifest import (
    MANIFEST_IDENTITY_NAMESPACE,
    MANIFEST_IDENTITY_VERSION,
    SUPPORTED_MANIFEST_SCHEMA_VERSIONS,
    CapabilityRequirement,
    ComponentReference,
    EdgeSpec,
    EventBinding,
    LifecycleEvent,
    ManifestMetadata,
    ManifestObject,
    NodeSpec,
    OutputSpec,
    ParameterSpec,
    StrategyManifest,
    canonical_strategy_json,
    deserialize_manifest,
    freeze_manifest_value,
    manifest_identity,
    manifest_to_data,
    manifest_value_to_data,
    serialize_manifest,
    validate_semantic_version,
    validate_strategy_identifier,
)
from strategies.registry import DEFAULT_REGISTRY, StrategyRegistry
from strategies.plugins import (
    PLUGIN_IDENTITY_NAMESPACE,
    PLUGIN_IDENTITY_VERSION,
    PLUGIN_SDK_VERSION,
    PluginMetadata,
    StrategyPlugin,
    build_plugin_registry,
)
from strategies.signal import StrategySignal
from strategies.type_system import (
    DEFAULT_TYPE_SYSTEM,
    TYPE_SYSTEM_VERSION,
    ComponentValues,
    StrategyTypeDefinition,
    StrategyTypeKind,
    StrategyTypeSystem,
    TypedValue,
    build_default_type_system,
)

__all__ = [
    "CompiledNode",
    "CompiledExpression",
    "CompiledStrategyGraph",
    "EVALUATION_IDENTITY_NAMESPACE",
    "EVALUATION_IDENTITY_VERSION",
    "COMPONENT_IDENTITY_NAMESPACE",
    "COMPONENT_IDENTITY_VERSION",
    "DEFAULT_REGISTRY",
    "DEFAULT_TYPE_SYSTEM",
    "REGISTRY_IDENTITY_NAMESPACE",
    "REGISTRY_IDENTITY_VERSION",
    "SUPPORTED_COMPONENT_CAPABILITIES",
    "TYPE_SYSTEM_VERSION",
    "BaseComponent",
    "CapabilityRequirement",
    "ComponentCategory",
    "ComponentContractError",
    "ComponentDefinition",
    "ComponentReference",
    "ComponentRegistry",
    "ComponentValues",
    "DuplicateStrategyRegistrationError",
    "EXPRESSION_IDENTITY_NAMESPACE",
    "EXPRESSION_IDENTITY_VERSION",
    "EXPRESSION_LANGUAGE_VERSION",
    "EdgeSpec",
    "ExpressionCompileError",
    "ExpressionError",
    "ExpressionEvaluationError",
    "ExpressionLimits",
    "ExpressionNode",
    "ExpressionResult",
    "ExpressionTrace",
    "ExecutionTrace",
    "GRAPH_IDENTITY_NAMESPACE",
    "GRAPH_IDENTITY_VERSION",
    "GRAPH_RUNTIME_VERSION",
    "GraphExecutionError",
    "GraphExecutionResult",
    "GraphValidationError",
    "EventBinding",
    "InvalidStrategyParameterError",
    "LifecycleEvent",
    "MANIFEST_IDENTITY_NAMESPACE",
    "MANIFEST_IDENTITY_VERSION",
    "ManifestMetadata",
    "ManifestObject",
    "ManifestSerializationError",
    "ManifestValidationError",
    "MissingIndicatorInputError",
    "NoContributingFactsError",
    "NodeSpec",
    "OPPORTUNITY_IDENTITY_NAMESPACE",
    "OPPORTUNITY_IDENTITY_VERSION",
    "PLUGIN_IDENTITY_NAMESPACE",
    "PLUGIN_IDENTITY_VERSION",
    "PLUGIN_SDK_VERSION",
    "OutputSpec",
    "ParameterDefinition",
    "ParameterSpec",
    "PortCardinality",
    "PortDefinition",
    "PluginMetadata",
    "SUPPORTED_MANIFEST_SCHEMA_VERSIONS",
    "StrategyError",
    "StrategyManifest",
    "StrategyPlugin",
    "StrategyRegistry",
    "StrategySignal",
    "StrategyTypeReference",
    "StrategyTypeDefinition",
    "StrategyTypeKind",
    "StrategyTypeSystem",
    "TypedValue",
    "TraceEvent",
    "UnsupportedManifestSchemaError",
    "UnknownStrategyIdError",
    "canonical_strategy_json",
    "build_default_type_system",
    "build_plugin_registry",
    "component_definition_data",
    "component_identity",
    "compile_expression",
    "compile_strategy_graph",
    "deserialize_manifest",
    "evaluate_strategy",
    "evaluate_expression",
    "execute_strategy_graph",
    "freeze_manifest_value",
    "manifest_identity",
    "manifest_to_data",
    "manifest_value_to_data",
    "opportunity_identity",
    "serialize_manifest",
    "validate_semantic_version",
    "validate_strategy_identifier",
]
