"""Strategy Layer (ADR-003).

Owns deterministic Strategy evaluation and Opportunity production. Narrower
dependency rule (ADR-004, ASA-CORE-005): may depend on strategies,
indicators, facts, reconciliation, and domain — not observation or
providers, even though both sit below strategies in the general pipeline
order (Constitution Law 4: Strategies consume knowledge, they do not
gather it).
"""
from strategies.components import (
    COMPONENT_IDENTITY_NAMESPACE,
    COMPONENT_IDENTITY_VERSION,
    BaseComponent,
    ComponentCategory,
    ComponentDefinition,
    ParameterDefinition,
    PortCardinality,
    PortDefinition,
    StrategyTypeReference,
    component_definition_data,
    component_identity,
)
from strategies.component_registry import (
    REGISTRY_IDENTITY_NAMESPACE,
    REGISTRY_IDENTITY_VERSION,
    SUPPORTED_COMPONENT_CAPABILITIES,
    ComponentRegistry,
)
from strategies.engine import (
    OPPORTUNITY_IDENTITY_NAMESPACE,
    OPPORTUNITY_IDENTITY_VERSION,
    evaluate_strategy,
    opportunity_identity,
)
from strategies.errors import (
    ComponentContractError,
    DuplicateStrategyRegistrationError,
    InvalidStrategyParameterError,
    ManifestSerializationError,
    ManifestValidationError,
    MissingIndicatorInputError,
    NoContributingFactsError,
    StrategyError,
    UnsupportedManifestSchemaError,
    UnknownStrategyIdError,
)
from strategies.manifest import (
    MANIFEST_IDENTITY_NAMESPACE,
    MANIFEST_IDENTITY_VERSION,
    SUPPORTED_MANIFEST_SCHEMA_VERSIONS,
    CapabilityRequirement,
    ComponentReference,
    EdgeSpec,
    EventBinding,
    LifecycleEvent,
    ManifestMetadata,
    ManifestObject,
    NodeSpec,
    OutputSpec,
    ParameterSpec,
    StrategyManifest,
    canonical_strategy_json,
    deserialize_manifest,
    freeze_manifest_value,
    manifest_identity,
    manifest_to_data,
    manifest_value_to_data,
    serialize_manifest,
    validate_semantic_version,
    validate_strategy_identifier,
)
from strategies.registry import DEFAULT_REGISTRY, StrategyRegistry
from strategies.signal import StrategySignal
from strategies.type_system import (
    DEFAULT_TYPE_SYSTEM,
    TYPE_SYSTEM_VERSION,
    ComponentValues,
    StrategyTypeDefinition,
    StrategyTypeKind,
    StrategyTypeSystem,
    TypedValue,
    build_default_type_system,
)

__all__ = [
    "COMPONENT_IDENTITY_NAMESPACE",
    "COMPONENT_IDENTITY_VERSION",
    "DEFAULT_REGISTRY",
    "DEFAULT_TYPE_SYSTEM",
    "REGISTRY_IDENTITY_NAMESPACE",
    "REGISTRY_IDENTITY_VERSION",
    "SUPPORTED_COMPONENT_CAPABILITIES",
    "TYPE_SYSTEM_VERSION",
    "BaseComponent",
    "CapabilityRequirement",
    "ComponentCategory",
    "ComponentContractError",
    "ComponentDefinition",
    "ComponentReference",
    "ComponentRegistry",
    "ComponentValues",
    "DuplicateStrategyRegistrationError",
    "EdgeSpec",
    "EventBinding",
    "InvalidStrategyParameterError",
    "LifecycleEvent",
    "MANIFEST_IDENTITY_NAMESPACE",
    "MANIFEST_IDENTITY_VERSION",
    "ManifestMetadata",
    "ManifestObject",
    "ManifestSerializationError",
    "ManifestValidationError",
    "MissingIndicatorInputError",
    "NoContributingFactsError",
    "NodeSpec",
    "OPPORTUNITY_IDENTITY_NAMESPACE",
    "OPPORTUNITY_IDENTITY_VERSION",
    "OutputSpec",
    "ParameterDefinition",
    "ParameterSpec",
    "PortCardinality",
    "PortDefinition",
    "SUPPORTED_MANIFEST_SCHEMA_VERSIONS",
    "StrategyError",
    "StrategyManifest",
    "StrategyRegistry",
    "StrategySignal",
    "StrategyTypeReference",
    "StrategyTypeDefinition",
    "StrategyTypeKind",
    "StrategyTypeSystem",
    "TypedValue",
    "UnsupportedManifestSchemaError",
    "UnknownStrategyIdError",
    "canonical_strategy_json",
    "build_default_type_system",
    "component_definition_data",
    "component_identity",
    "deserialize_manifest",
    "evaluate_strategy",
    "freeze_manifest_value",
    "manifest_identity",
    "manifest_to_data",
    "manifest_value_to_data",
    "opportunity_identity",
    "serialize_manifest",
    "validate_semantic_version",
    "validate_strategy_identifier",
]
