"""Shared domain module (ADR-004 `domain/`).

Cross-cutting, immutable value types referenced by multiple layers —
defined once here, referenced everywhere (Constitution Law 3). Structural
definitions only; no business logic lives in this package (ASA-CORE-001).

Depends on nothing but itself and the standard library.
"""

from domain.canonical_fact import CanonicalFact
from domain.execution import (
    ExecutionPlanningEvent,
    ExecutionPlanningEventType,
    ExecutionPlanningLifecycle,
    ExecutionPlan,
    ExecutionSummary,
    PlannedOrder,
    PlannedOrderSide,
    PlannedOrderStatus,
    PlannedOrderType,
    PlanningTrace,
    PlanningTraceEvent,
    PlanningTraceEventType,
    PolicyOutcome,
    PortfolioDelta,
    PortfolioDeltaKind,
    PortfolioEvaluationDisposition,
    PortfolioEvaluationResult,
    RiskDecision,
    RiskDecisionState,
    TimeInForce,
)
from domain.financial import (
    FINANCIAL_CONTRACT_VERSION,
    AnnouncementTime,
    EarningsCalendar,
    EarningsEvent,
    EarningsHistoryEntry,
    ExpirationCollection,
    ExpirationCycle,
    FinancialContractSerializationError,
    OptionChain,
    OptionCollection,
    OptionContract,
    OptionLeg,
    OptionLegPosition,
    OptionStructure,
    OptionStructureType,
    OptionType,
    Security,
    SecurityAssetType,
    SecurityCollection,
    VolatilityEvidence,
    deserialize_financial_contract,
    financial_contract_to_data,
    serialize_financial_contract,
)
from domain.guardrail import GuardrailOutcome
from domain.indicator import Indicator
from domain.market_data import (
    MARKET_DATA_CONTRACT_VERSION,
    CompletenessMetadata,
    CorporateActionPlaceholder,
    CorporateActionStatus,
    CorporateActionType,
    FreshnessMetadata,
    FreshnessStatus,
    MarketCapability,
    MarketDataRequestContext,
    MarketDataSubject,
    MarketDataSubjectType,
    MarketObservation,
    NormalizedProviderErrorMetadata,
    OHLCVBar,
    ProviderErrorKind,
    ProviderAddressProjection,
    ProviderProvenance,
    Quote,
    TradingCalendarEvent,
    TradingCalendarEventType,
    deserialize_market_data,
    market_data_to_data,
    market_observation_identity,
    serialize_market_data,
)
from domain.observation import Observation
from domain.opportunity import Opportunity, RecommendationState
from domain.operational import (
    CanonicalInstrumentIdentity,
    InstrumentValuation,
    Instrument,
    InstrumentKind,
    MonetaryAmount,
    Portfolio,
    PortfolioEvaluationRequest,
    PortfolioSnapshot,
    PositionDirection,
    Position,
    ProposedPosition,
    RiskPolicy,
    RiskPolicyScope,
    RiskPolicyType,
    SectorClassification,
)
from domain.outcome_metrics import ExpectedOutcomeMetrics
from domain.provenance import Provenance, ProviderDisagreement
from domain.provider import Provider
from domain.references import Confidence, EvidenceKind, EvidenceReference
from domain.replay import ExecutionReplayRecord, ReplayVerification
from domain.simulation import (
    SimulatedFill,
    SimulatedOrderState,
    SimulationFrame,
    SimulationMarketData,
    SimulationResult,
    SimulationTerminalReason,
    SimulationTraceEvent,
    SimulationTraceEventType,
)
from domain.values import DomainInvariantError, is_normalized_value

__all__ = [
    "CanonicalFact",
    "CanonicalInstrumentIdentity",
    "Confidence",
    "DomainInvariantError",
    "is_normalized_value",
    "EvidenceKind",
    "EvidenceReference",
    "ExpectedOutcomeMetrics",
    "ExecutionPlanningEvent",
    "ExecutionPlanningEventType",
    "ExecutionPlanningLifecycle",
    "ExecutionPlan",
    "ExecutionReplayRecord",
    "ExecutionSummary",
    "FINANCIAL_CONTRACT_VERSION",
    "FinancialContractSerializationError",
    "GuardrailOutcome",
    "AnnouncementTime",
    "EarningsCalendar",
    "EarningsEvent",
    "EarningsHistoryEntry",
    "ExpirationCollection",
    "ExpirationCycle",
    "InstrumentValuation",
    "Indicator",
    "Instrument",
    "InstrumentKind",
    "MonetaryAmount",
    "MARKET_DATA_CONTRACT_VERSION",
    "MarketCapability",
    "MarketDataRequestContext",
    "MarketDataSubject",
    "MarketDataSubjectType",
    "MarketObservation",
    "Quote",
    "OHLCVBar",
    "TradingCalendarEvent",
    "TradingCalendarEventType",
    "CorporateActionPlaceholder",
    "CorporateActionType",
    "CorporateActionStatus",
    "FreshnessMetadata",
    "FreshnessStatus",
    "CompletenessMetadata",
    "ProviderProvenance",
    "ProviderErrorKind",
    "ProviderAddressProjection",
    "NormalizedProviderErrorMetadata",
    "Observation",
    "OptionChain",
    "OptionCollection",
    "OptionContract",
    "OptionLeg",
    "OptionLegPosition",
    "OptionStructure",
    "OptionStructureType",
    "OptionType",
    "Opportunity",
    "PlannedOrder",
    "PlannedOrderSide",
    "PlannedOrderStatus",
    "PlannedOrderType",
    "PlanningTrace",
    "PlanningTraceEvent",
    "PlanningTraceEventType",
    "PolicyOutcome",
    "Portfolio",
    "PortfolioDelta",
    "PortfolioDeltaKind",
    "PortfolioEvaluationDisposition",
    "PortfolioEvaluationRequest",
    "PortfolioEvaluationResult",
    "PortfolioSnapshot",
    "PositionDirection",
    "Position",
    "Provenance",
    "Provider",
    "ProviderDisagreement",
    "ProposedPosition",
    "RiskDecision",
    "RiskDecisionState",
    "RiskPolicy",
    "RiskPolicyScope",
    "RiskPolicyType",
    "RecommendationState",
    "ReplayVerification",
    "Security",
    "SecurityAssetType",
    "SecurityCollection",
    "SimulatedFill",
    "SimulatedOrderState",
    "SimulationFrame",
    "SimulationMarketData",
    "SimulationResult",
    "SimulationTerminalReason",
    "SimulationTraceEvent",
    "SimulationTraceEventType",
    "SectorClassification",
    "TimeInForce",
    "VolatilityEvidence",
    "deserialize_financial_contract",
    "financial_contract_to_data",
    "serialize_financial_contract",
    "deserialize_market_data",
    "market_data_to_data",
    "market_observation_identity",
    "serialize_market_data",
]
